CREATE TABLE "user" (
	"id"	INTEGER NOT NULL,
	"name"	TEXT NOT NULL DEFAULT '',
	"username"	TEXT NOT NULL DEFAULT '' UNIQUE,
	"password"	CHAR(20) NOT NULL DEFAULT '',
	"created_at"	TEXT NOT NULL DEFAULT '0000-00-00 00:00:00',
	"updated_at"	TEXT NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY("id" AUTOINCREMENT)
);